### PR TITLE
Switch to Angular CLI build

### LINKED ISSUE #4: Cannot build with --aot mode
```
ERROR in ./src/app/app.module.ngfactory.js
Module not found: Error: Can't resolve 'ngx-translate-phraseapp/dist/compiler' in ...
```

After AoT compilation, all imports from `'ngx-translate-phaseapp'` is converted to local paths like `ngx-translate-phraseapp/dist/compiler`. but published artifact only includes one UMD bundle.

It should support FESM library packaging format like ngx-translate. (https://unpkg.com/@ngx-translate/core@10.0.2/)
Angular CLI v6 supports the format.  

BTW, can I solve this issue by sending PR?

### PR DESCRIPTION
**Pull request by lacolaco**
Fix #4

### CODE REVIEW

**Comment by theSoenke** [comment]
@lacolaco Thank you very much. This looks really good. Unfortunately it currently breaks the the [demo application](https://github.com/phrase/ngx-translate-phraseapp-demo) as it cannot find the module `ngx-translate-phraseapp` anymore. When we can resolve this I will happily merge this PR

**Comment by lacolaco** [comment]
any update on this?

**Comment by theSoenke** [comment]
@lacolaco One thing missing is the entrypoint in the package.json. Otherwise it cannot be imported as a package. At least when I tried it with the demo project

**Comment by theSoenke** [comment]
I have looked into it to fix the remaining issue when using this as a library but was not successful so far. As this currently breaks the library I will close this Pull Request for now. In case you see a fix for this I will reopen and merge this PR right away

**Pull request closed without merging**
